// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADMVVNeOsa5tioli08581d94Z6hiAiB9U',
    appId: '1:960706587842:web:c437102f64d1226f939f5b',
    messagingSenderId: '960706587842',
    projectId: 'ttgo-app-7cc36',
    authDomain: 'ttgo-app-7cc36.firebaseapp.com',
    storageBucket: 'ttgo-app-7cc36.firebasestorage.app',
    measurementId: 'G-E45340K1NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqtH3QyjmXWo6dtkCKKpP7Yf7I0HzfBbE',
    appId: '1:960706587842:android:522893200afaa82d939f5b',
    messagingSenderId: '960706587842',
    projectId: 'ttgo-app-7cc36',
    storageBucket: 'ttgo-app-7cc36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbO-TzccOXiwvC4m_iA38BP8wZR9qr9A',
    appId: '1:960706587842:ios:6a361609a0b99fbd939f5b',
    messagingSenderId: '960706587842',
    projectId: 'ttgo-app-7cc36',
    storageBucket: 'ttgo-app-7cc36.firebasestorage.app',
    iosBundleId: 'com.example.ttgoFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACbO-TzccOXiwvC4m_iA38BP8wZR9qr9A',
    appId: '1:960706587842:ios:6a361609a0b99fbd939f5b',
    messagingSenderId: '960706587842',
    projectId: 'ttgo-app-7cc36',
    storageBucket: 'ttgo-app-7cc36.firebasestorage.app',
    iosBundleId: 'com.example.ttgoFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADMVVNeOsa5tioli08581d94Z6hiAiB9U',
    appId: '1:960706587842:web:0b4b4a79cdd1926e939f5b',
    messagingSenderId: '960706587842',
    projectId: 'ttgo-app-7cc36',
    authDomain: 'ttgo-app-7cc36.firebaseapp.com',
    storageBucket: 'ttgo-app-7cc36.firebasestorage.app',
    measurementId: 'G-NQHVRFGC30',
  );
}
